language: node_js
node_js:
- '5.1'
- '6.0'
sudo: false
services:
before_install:
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/mission-io/mission.api/npm-debug.log
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      #
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
